"use client";

import React, { useState } from "react";
import type { RoadmapResponse } from "@/lib/schemas";
import {
  DownloadIcon,
  PrinterIcon,
  CheckIcon,
  SparklesIcon,
} from "./icons/Icons";

interface ExportModalProps {
  roadmap: RoadmapResponse;
  completedTaskIds: string[];
  isOpen: boolean;
  onClose: () => void;
}

export function ExportModal({
  roadmap,
  completedTaskIds,
  isOpen,
  onClose,
}: ExportModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  // Generate Markdown representation
  const generateMarkdown = () => {
    let md = `# ${roadmap.title}\n\n`;
    md += `**Target Role**: ${roadmap.careerGoal}\n`;
    md += `**Experience Level**: ${roadmap.experienceLevel}\n`;
    md += `**Commitment**: ${roadmap.hoursPerWeek} hrs/week\n`;
    md += `**Target Duration**: ${roadmap.targetDuration}\n`;
    md += `**Total Estimated Hours**: ${roadmap.totalEstimatedHours} hours\n\n`;
    md += `## Overview\n${roadmap.summary}\n\n`;

    md += `## Phases & Milestones\n\n`;
    roadmap.phases.forEach((phase) => {
      md += `### Phase ${phase.phaseNumber}: ${phase.title}\n`;
      md += `*Estimated Time*: ${phase.estimatedWeeks} weeks (~${phase.estimatedHours} hours)\n\n`;
      md += `${phase.description}\n\n`;

      if (phase.milestoneProject) {
        md += `#### 🏆 Milestone Project: ${phase.milestoneProject.title}\n`;
        md += `${phase.milestoneProject.description}\n\n`;
        md += `*Deliverables*:\n`;
        phase.milestoneProject.deliverables.forEach((deliv) => {
          md += `- [ ] ${deliv}\n`;
        });
        md += `\n`;
      }

      md += `#### Tasks\n`;
      phase.tasks.forEach((task) => {
        const isDone = completedTaskIds.includes(task.id);
        md += `- [${isDone ? "x" : " "}] **${task.title}** (${task.estimatedHours} hrs) - ${task.category.toUpperCase()}\n`;
        md += `  ${task.description}\n`;
        if (task.resources && task.resources.length > 0) {
          md += `  *Resources*: ${task.resources.map((r) => `[${r.title}](${r.url})`).join(", ")}\n`;
        }
        if (task.tips) {
          md += `  *Tip*: ${task.tips}\n`;
        }
      });
      md += `\n`;
    });

    if (roadmap.careerInsights) {
      md += `## Industry & Career Insights\n\n`;
      md += `### In-Demand Skills\n`;
      roadmap.careerInsights.inDemandSkills.forEach((s) => (md += `- ${s}\n`));
      md += `\n### Recommended Certifications\n`;
      roadmap.careerInsights.recommendedCertifications.forEach((c) => (md += `- ${c}\n`));
      md += `\n### Portfolio Project Tips\n`;
      roadmap.careerInsights.portfolioTips.forEach((p) => (md += `- ${p}\n`));
      md += `\n### Interview Prep Focus\n`;
      roadmap.careerInsights.interviewPrepFocus.forEach((i) => (md += `- ${i}\n`));
    }

    md += `\n---\n*Generated by PathPilot AI - Personalized Career Roadmap Platform*\n`;
    return md;
  };

  const handleDownloadMarkdown = () => {
    const mdContent = generateMarkdown();
    const blob = new Blob([mdContent], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${roadmap.careerGoal.toLowerCase().replace(/\s+/g, "-")}-roadmap.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadJSON = () => {
    const jsonContent = JSON.stringify(
      {
        ...roadmap,
        exportedCompletedTaskIds: completedTaskIds,
      },
      null,
      2
    );
    const blob = new Blob([jsonContent], { type: "application/json;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${roadmap.careerGoal.toLowerCase().replace(/\s+/g, "-")}-roadmap.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopyClipboard = async () => {
    try {
      const md = generateMarkdown();
      await navigator.clipboard.writeText(md);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      console.error("Clipboard copy failed");
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200"
      role="dialog"
      aria-modal="true"
      aria-labelledby="export-modal-title"
      onClick={onClose}
    >
      <div
        className="relative w-full max-w-lg rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 sm:p-8 shadow-2xl space-y-6"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between pb-4 border-b border-slate-100 dark:border-slate-800">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-indigo-50 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400">
              <DownloadIcon className="w-5 h-5" />
            </div>
            <div>
              <h2 id="export-modal-title" className="text-lg font-bold text-slate-900 dark:text-white">
                Export & Share Roadmap
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Save offline, integrate into Obsidian/Notion, or print.
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
            aria-label="Close export dialog"
          >
            ✕
          </button>
        </div>

        {/* Options Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {/* Option 1: Markdown */}
          <button
            type="button"
            onClick={handleDownloadMarkdown}
            className="p-4 rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/50 hover:border-indigo-500 dark:hover:border-indigo-500 transition-all text-left space-y-2 group focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
          >
            <div className="flex items-center justify-between">
              <span className="p-2 rounded-lg bg-indigo-100 dark:bg-indigo-900/60 text-indigo-700 dark:text-indigo-300 font-mono text-xs font-bold">
                .MD
              </span>
              <DownloadIcon className="w-4 h-4 text-slate-400 group-hover:text-indigo-500 transition-colors" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900 dark:text-white">Markdown Export</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Ideal for Obsidian, Notion, GitHub wikis & notes.
              </p>
            </div>
          </button>

          {/* Option 2: JSON */}
          <button
            type="button"
            onClick={handleDownloadJSON}
            className="p-4 rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/50 hover:border-indigo-500 dark:hover:border-indigo-500 transition-all text-left space-y-2 group focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
          >
            <div className="flex items-center justify-between">
              <span className="p-2 rounded-lg bg-emerald-100 dark:bg-emerald-900/60 text-emerald-700 dark:text-emerald-300 font-mono text-xs font-bold">
                .JSON
              </span>
              <DownloadIcon className="w-4 h-4 text-slate-400 group-hover:text-emerald-500 transition-colors" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900 dark:text-white">JSON Schema</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Full structured data with task timestamps.
              </p>
            </div>
          </button>

          {/* Option 3: Copy to Clipboard */}
          <button
            type="button"
            onClick={handleCopyClipboard}
            className="p-4 rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/50 hover:border-indigo-500 dark:hover:border-indigo-500 transition-all text-left space-y-2 group focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
          >
            <div className="flex items-center justify-between">
              <span className="p-2 rounded-lg bg-purple-100 dark:bg-purple-900/60 text-purple-700 dark:text-purple-300 font-mono text-xs font-bold">
                {copied ? "✓ Copied" : "CLIPBOARD"}
              </span>
              {copied ? (
                <CheckIcon className="w-4 h-4 text-emerald-500" />
              ) : (
                <SparklesIcon className="w-4 h-4 text-slate-400 group-hover:text-purple-500 transition-colors" />
              )}
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900 dark:text-white">Copy Markdown</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Paste directly into Discord, Slack, or Docs.
              </p>
            </div>
          </button>

          {/* Option 4: Print / PDF */}
          <button
            type="button"
            onClick={handlePrint}
            className="p-4 rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/50 hover:border-indigo-500 dark:hover:border-indigo-500 transition-all text-left space-y-2 group focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
          >
            <div className="flex items-center justify-between">
              <span className="p-2 rounded-lg bg-amber-100 dark:bg-amber-900/60 text-amber-700 dark:text-amber-300 font-mono text-xs font-bold">
                PRINT / PDF
              </span>
              <PrinterIcon className="w-4 h-4 text-slate-400 group-hover:text-amber-500 transition-colors" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900 dark:text-white">Print View</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Browser print formatted for PDF saving.
              </p>
            </div>
          </button>
        </div>

        <div className="pt-2 flex justify-end">
          <button
            type="button"
            onClick={onClose}
            className="px-5 py-2.5 rounded-xl text-sm font-semibold bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 hover:bg-slate-200 dark:hover:bg-slate-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
}
